### ISSUE TITLE
Общий функционал

### ISSUE THREAD

**Issue by mrerro** [profcomff/print-tgbot#1]
1. При старте выводить небольшое приветствие и инструкцию пользования и кнопку авторизоваться.
2. При нажатии кнопки авторизоваться провести диалог:
    1. Напиши мне свою фамилию.
    2. Напиши мне номер профсоюзного билета.
    3. Проводится проверка введенных данных.
        1. Записать в базу chat.id как авторизованный для следующих проверок.
        2. Если все хорошо то сообщение вы успешно авторизованы и мини инструкцию что теперь ты можешь присылать мне файл pdf.
        3. Если нет то снова показать кнопку авторизоваться из пункта 1.
3. Пользователь кидает pdf.
    1. Мы проверяем что пользователь в базе. Если нет то пункт 1. 
    2. Запускаем диалог **TODO надо подумать**
        1. показываем диалог напечатать весь документ или настроить страницы
        2. показываем инструкцию как корректно указать страницы
        3. если нет просим повторить
        4. если корректно показываем кнопки односторонняя печать или 2х сторонняя
        5. показываем кнопки с количеством копий (допустим 5 кнопок 1-5)
    3. Нужно ли возможность сбросить диалог? или первый выбор давать стандартные настройки или настроить самому

**Comment by Annndruha** [comment]
Общий функционал реализован в полном объёме.

P.s. Кстати идея о выборе количества копий через пять кнопок норм. Мб изменим.
